sudo: "required"
dist: "trusty"
language: "node_js"
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
env:
  global:
    # GH_TOKEN and NPM_TOKEN encrypted by 'travis encrypt' utility
    - secure: "gO5DrzOfF+l3hjvs0kLYUrGEnYVwrDy7NTGNrtPmLrrfdS6qmUNbTVggjra2aDM82lZYo0slZaOtjedSd8GMNE41egHAq0aGMJfhNrXjr+ROOIkc1BRUn3vTp5lk/n4eU7bLozoiriBphmKHHwZqekSn2orvIpAtoWL/JPVzheY="
cache:
  directories:
    - "node_modules"
before_install:
  - "npm -g install npm@latest"
  - "gem install travis"
  - "curl -Lo travis_after_all.py https://raw.githubusercontent.com/dmakhno/travis_after_all/master/travis_after_all.py"
before_script:
  - "npm run lint"
script:
  - "npm test"
  - "npm run test:hooks-handlers"
after_success:  # travis_after_all.py is needed due to travis-ci/travis-ci#1548 & travis-ci/travis-ci#929
  - "npm run coveralls"
  - "python travis_after_all.py"
  - "export $(cat .to_export_back)"
  - "npm run semantic-release || true"
